name: AutoRelease

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake make
      run:  mkdir build && cd ./build && cmake ..
    - name: configure
      run: ./build/configure
    - name: make
      run: cd build && make
    - name: make check
      run: cd build && make check
    - name: make distcheck
      run: cd build && make distcheck
